# Generated by Django 3.1 on 2024-10-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Matchdetails',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.event')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('representative_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.department')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('coach', models.CharField(max_length=100)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.representative')),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('standing_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.team')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('draw', models.BooleanField(default=False)),
                ('loser_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser_team', to='sports.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.matchdetails')),
                ('winner_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='sports.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.team')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('posted_date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.event')),
            ],
        ),
        migrations.CreateModel(
            name='Livescore',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.matchdetails')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.team')),
            ],
        ),
        migrations.CreateModel(
            name='Handball',
            fields=[
                ('handball_match_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('goals_team1', models.IntegerField()),
                ('goals_team2', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.matchdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Football',
            fields=[
                ('football_match_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('goals_team1', models.IntegerField()),
                ('goals_team2', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.matchdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('cricket_match_id', models.AutoField(primary_key=True, serialize=False)),
                ('overs', models.IntegerField()),
                ('runs_team1', models.IntegerField()),
                ('runs_team2', models.IntegerField()),
                ('wickets_team1', models.IntegerField()),
                ('wickets_team2', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.matchdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Chess',
            fields=[
                ('chess_match_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('moves', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.matchdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Carom',
            fields=[
                ('carom_match_id', models.AutoField(primary_key=True, serialize=False)),
                ('rounds', models.IntegerField()),
                ('points_team1', models.IntegerField()),
                ('points_team2', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.matchdetails')),
            ],
        ),
    ]
